### ISSUE TITLE
pip installs old version

### ISSUE THREAD

**Issue by oldskool** [MTSolutions/superslacker#7]
When following the documentation, using `pip install superslacker` gave me an old version that does not yet support the --webhook option. It only accepts a legacy token and channel.

I should probably do a manual install to fix this, but is there any way the pip version could be bumped? Would make it easier to deploy superslacker to my servers running supervisor.

**Comment by slara** [comment]
Hi @oldskool, the pypi package has been updated. I will close this issue for now. Feel free to reopen it if needed.

**Comment by oldskool** [comment]
Thank you for the fast response/follow-up @slara !
pip now installs the latest version 👍
